//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DependencyInj.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int SNo { get; set; }
        public string Sname { get; set; }
        public string Saddr { get; set; }
    }
}
